---
kind: pipeline
type: docker
name: default

steps:
- name: build launcher
  image: eclipse-temurin:11
  volumes:
  - name: yabko_root
    path: /tmp/yabko_root
  commands:
  - ./gradlew build
  - export version=$$(grep -oP "version = '\K[0-9\.]*" build.gradle)
  - cp launcher-builder/build/libs/launcher-builder-$${version}.jar modpack-builder.jar
  - cp launcher-fancy/build/libs/launcher-fancy-$${version}.jar /tmp/yabko_root/launcher/versions/
  - echo "{\"version\":\"$${version}\",\"url\":\"$${LAUNCHER_URL}launcher-fancy-$${version}.jar\"}" > /tmp/yabko_root/launcher/latest.json
  environment:
    LAUNCHER_URL:
      from_secret: launcher_url

- name: build modpack-builder docker image
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker build -t modpack-builder:latest -f builder_Dockerfile .

volumes:
- name: dockersock
  host:
    path: /var/run
- name: yabko_root
  host:
    path: /data/yabko_root/www

trigger:
  branch:
  - master
